
//! Autogenerated weights for `peaq_pallet_rbac`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-05-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `drping-m16`, CPU: `12th Gen Intel(R) Core(TM) i9-12900H`
//! EXECUTION: Some(Native), WASM-EXECUTION: Compiled, CHAIN: Some("dev-local"), DB CACHE: 1024

// Executed Command:
// ./target/release/peaq-node
// benchmark
// pallet
// --chain=dev-local
// --execution=native
// --wasm-execution=compiled
// --pallet=peaq-pallet-rbac
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `peaq_pallet_rbac`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac RoleStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac RoleStore (max_values: None, max_size: None, mode: Measured)
	fn add_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 30_600_000 picoseconds.
		Weight::from_parts(32_456_000, 0)
			.saturating_add(Weight::from_parts(0, 3541))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac RoleStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac RoleStore (max_values: None, max_size: None, mode: Measured)
	fn update_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 49_210_000 picoseconds.
		Weight::from_parts(53_526_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac RoleStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac RoleStore (max_values: None, max_size: None, mode: Measured)
	fn disable_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 52_401_000 picoseconds.
		Weight::from_parts(55_159_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `3751`
		// Minimum execution time: 26_015_000 picoseconds.
		Weight::from_parts(28_027_000, 0)
			.saturating_add(Weight::from_parts(0, 3751))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac RoleStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac RoleStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_roles() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `386`
		//  Estimated: `3851`
		// Minimum execution time: 27_187_000 picoseconds.
		Weight::from_parts(27_696_000, 0)
			.saturating_add(Weight::from_parts(0, 3851))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac Role2UserStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac Role2UserStore (max_values: None, max_size: None, mode: Measured)
	fn assign_role_to_user() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3680`
		// Minimum execution time: 56_688_000 picoseconds.
		Weight::from_parts(57_563_000, 0)
			.saturating_add(Weight::from_parts(0, 3680))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac Role2UserStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac Role2UserStore (max_values: None, max_size: None, mode: Measured)
	fn unassign_role_to_user() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3750`
		// Minimum execution time: 26_505_000 picoseconds.
		Weight::from_parts(27_325_000, 0)
			.saturating_add(Weight::from_parts(0, 3750))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:2 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac Role2GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac Role2GroupStore (max_values: None, max_size: None, mode: Measured)
	fn assign_role_to_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `338`
		//  Estimated: `6278`
		// Minimum execution time: 30_001_000 picoseconds.
		Weight::from_parts(30_870_000, 0)
			.saturating_add(Weight::from_parts(0, 6278))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac Role2GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac Role2GroupStore (max_values: None, max_size: None, mode: Measured)
	fn unassign_role_to_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `3783`
		// Minimum execution time: 27_055_000 picoseconds.
		Weight::from_parts(30_082_000, 0)
			.saturating_add(Weight::from_parts(0, 3783))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac Role2UserStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Role2UserStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_user_roles() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3750`
		// Minimum execution time: 24_186_000 picoseconds.
		Weight::from_parts(25_834_000, 0)
			.saturating_add(Weight::from_parts(0, 3750))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac PermissionStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac PermissionStore (max_values: None, max_size: None, mode: Measured)
	fn add_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 32_417_000 picoseconds.
		Weight::from_parts(32_763_000, 0)
			.saturating_add(Weight::from_parts(0, 3541))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac PermissionStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac PermissionStore (max_values: None, max_size: None, mode: Measured)
	fn update_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 54_830_000 picoseconds.
		Weight::from_parts(55_445_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac PermissionStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac PermissionStore (max_values: None, max_size: None, mode: Measured)
	fn disable_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 48_952_000 picoseconds.
		Weight::from_parts(52_650_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `3751`
		// Minimum execution time: 23_836_000 picoseconds.
		Weight::from_parts(25_243_000, 0)
			.saturating_add(Weight::from_parts(0, 3751))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac PermissionStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac PermissionStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_permissions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `386`
		//  Estimated: `3851`
		// Minimum execution time: 25_390_000 picoseconds.
		Weight::from_parts(25_974_000, 0)
			.saturating_add(Weight::from_parts(0, 3851))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:2 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac Permission2RoleStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac Permission2RoleStore (max_values: None, max_size: None, mode: Measured)
	fn assign_permission_to_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `338`
		//  Estimated: `6278`
		// Minimum execution time: 28_540_000 picoseconds.
		Weight::from_parts(31_359_000, 0)
			.saturating_add(Weight::from_parts(0, 6278))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac Permission2RoleStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac Permission2RoleStore (max_values: None, max_size: None, mode: Measured)
	fn unassign_permission_to_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `3783`
		// Minimum execution time: 25_359_000 picoseconds.
		Weight::from_parts(27_250_000, 0)
			.saturating_add(Weight::from_parts(0, 3783))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac Permission2RoleStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Permission2RoleStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_role_permissions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `3783`
		// Minimum execution time: 23_574_000 picoseconds.
		Weight::from_parts(24_444_000, 0)
			.saturating_add(Weight::from_parts(0, 3783))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac GroupStore (max_values: None, max_size: None, mode: Measured)
	fn add_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 31_824_000 picoseconds.
		Weight::from_parts(32_568_000, 0)
			.saturating_add(Weight::from_parts(0, 3541))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac GroupStore (max_values: None, max_size: None, mode: Measured)
	fn update_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 49_479_000 picoseconds.
		Weight::from_parts(53_298_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac GroupStore (max_values: None, max_size: None, mode: Measured)
	fn disable_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 52_091_000 picoseconds.
		Weight::from_parts(52_603_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286`
		//  Estimated: `3751`
		// Minimum execution time: 26_694_000 picoseconds.
		Weight::from_parts(28_257_000, 0)
			.saturating_add(Weight::from_parts(0, 3751))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac GroupStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac GroupStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_groups() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `386`
		//  Estimated: `3851`
		// Minimum execution time: 27_648_000 picoseconds.
		Weight::from_parts(28_055_000, 0)
			.saturating_add(Weight::from_parts(0, 3851))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac User2GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac User2GroupStore (max_values: None, max_size: None, mode: Measured)
	fn assign_user_to_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3680`
		// Minimum execution time: 27_356_000 picoseconds.
		Weight::from_parts(29_015_000, 0)
			.saturating_add(Weight::from_parts(0, 3680))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac User2GroupStore (r:1 w:1)
	/// Proof Skipped: PeaqRbac User2GroupStore (max_values: None, max_size: None, mode: Measured)
	fn unassign_user_to_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3750`
		// Minimum execution time: 25_337_000 picoseconds.
		Weight::from_parts(27_026_000, 0)
			.saturating_add(Weight::from_parts(0, 3750))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PeaqRbac User2GroupStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac User2GroupStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_user_groups() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3750`
		// Minimum execution time: 22_289_000 picoseconds.
		Weight::from_parts(23_991_000, 0)
			.saturating_add(Weight::from_parts(0, 3750))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: PeaqRbac Role2UserStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Role2UserStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac User2GroupStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac User2GroupStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac Role2GroupStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Role2GroupStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac Permission2RoleStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Permission2RoleStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_user_permissions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `837`
		//  Estimated: `4302`
		// Minimum execution time: 49_991_000 picoseconds.
		Weight::from_parts(54_595_000, 0)
			.saturating_add(Weight::from_parts(0, 4302))
			.saturating_add(T::DbWeight::get().reads(5))
	}
	/// Storage: PeaqRbac Role2GroupStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Role2GroupStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac Permission2RoleStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Permission2RoleStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: PeaqRbac KeysLookUpStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac KeysLookUpStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_group_permissions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699`
		//  Estimated: `4164`
		// Minimum execution time: 42_099_000 picoseconds.
		Weight::from_parts(43_386_000, 0)
			.saturating_add(Weight::from_parts(0, 4164))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: PeaqRbac Role2GroupStore (r:1 w:0)
	/// Proof Skipped: PeaqRbac Role2GroupStore (max_values: None, max_size: None, mode: Measured)
	fn fetch_group_roles() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `3783`
		// Minimum execution time: 25_941_000 picoseconds.
		Weight::from_parts(26_443_000, 0)
			.saturating_add(Weight::from_parts(0, 3783))
			.saturating_add(T::DbWeight::get().reads(1))
	}

	// TODO benchmark these
	fn delete_role() -> Weight {
		Default::default()
	}

	fn delete_permission() -> Weight {
		Default::default()
	}

	fn delete_group() -> Weight {
		Default::default()
	}
}
